name: Django CI

on:
  pull_request:
    branches:
      - stage

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Stage Branch
      uses: actions/checkout@v2
      with:
        ref: refs/pull/${{ github.event.number }}/merge

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
    
    - name: Run Tests
      run: |
        python manage.py test
